logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.javatutorial: INFO


spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.HANAColumnStoreDialect

  liquibase:

    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: dev


